Feat: usage of axios for requests
CheesecakeLabs/front-end-boilerplate pull request #28
Opened 2020-01-18 21:34 UTC by caian-gums

This PR adds the usage of [axios](https://github.com/axios/axios) for making requests.

Related Issue: #22 

This PR contains
- `.env.example` file with the `API_URL` env var
- a configuration enabling `static` attributes and methods for the [babel plugin](https://babeljs.io/docs/en/next/babel-plugin-proposal-class-properties.html)
- `http` function that encapsulate `axios` with interceptor for Auth requests

2020-01-20 13:06 UTC, helderberto requested changes
@caian-gums reading the [axios code base](https://github.com/axios/axios/blob/master/lib/axios.js), we could use the [axios.create](https://github.com/axios/axios/blob/351cf290f0478d6e47e74c6da2f3ad8fe8f29887/lib/axios.js#L35) and reuse the instance.

We could think together and make a more simple use of axios.

2020-01-20 18:37 UTC, goodsmith submitted a review, later dismissed
LGTM

2020-01-21 00:21 UTC, smaniotto requested changes

2020-01-21 13:45 UTC, helderberto approved these changes

2020-01-22 16:53 UTC, smaniotto approved these changes

2020-02-07 20:13 UTC, merged